// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lubfehdynarfcskleimf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1YmZlaGR5bmFyZmNza2xlaW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTM2NDksImV4cCI6MjA2MTc2OTY0OX0.D3aRNLaFApxn3ubrlD9zBWZqiKZkJCcystvXb-mynDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);